build:
    image: emscripten/emsdk
    script:
        - make -C drawio-web
        - make -C web
    cache:
      paths:
        - web/dest/
        - /emsdk/upstream/emscripten/cache/
    artifacts:
      paths:
        - web/index.html
        - web/script.js
        - web/apo.js
        - web/apo.wasm
        - drawio-web/index.html
        - drawio-web/script.js
        - drawio-web/worker.js
        - drawio-web/pkg.tgz

