build:
    when: manual
    image: emscripten/emsdk
    script:
        - free > info.txt
        - cat /proc/cpuinfo >> info.txt
        - clang --version > toolchain.txt
        - wasm-ld --version >> toolchain.txt
        - wasm-opt --version >> toolchain.txt
        - emcc --version >> toolchain.txt
        - make -C drawio-web
        - make -C web
        - ls -lR dest >> dest.txt
    cache:
      paths:
        - web/dest/
        - /emsdk/upstream/emscripten/cache/
    artifacts:
      paths:
        - web/index.html
        - web/script.js
        - web/apo.js
        - web/apo.wasm
        - drawio-web/index.html
        - drawio-web/script.js
        - drawio-web/worker.js
        - drawio-web/pkg.tgz
        - toolchain.txt
        - dest.txt
        - info.txt

