#!/bin/sh
#
emcc  --no-entry -sMALLOC=emmalloc -sEXPORTED_FUNCTIONS="_apo_parse_tmp" -sDEFAULT_LIBRARY_FUNCS_TO_INCLUDE='[$ccall,$FS]' -sENVIRONMENT=web -Oz -sASSERTIONS=0 -sALLOW_MEMORY_GROWTH=1 -sINVOKE_RUN=0 -o apo.js ../apo.c ../rgc.c ../xml.c

