#!/bin/sh
set -x
o=$(pwd)
d=$(mktemp -d)
cd $d
curl https://gitlab.dsi.universite-paris-saclay.fr/alexandre.janon/apogee2drawio/-/archive/main/apogee2drawio-main.tar.gz | tar zxv
cd apogee2drawio-main
php $o/mktar.php > pkg.tar
zopfli --i50 pkg.tar
scp pkg.tar.gz sasmath:wwwdoc/apogee2drawio/pkg.tgz

